baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Sarosh Mirza"

# Enable taxonomies for blog categories
disableKinds = ["RSS"]

[params]
images = ["img/og-image.jpg"]
author = "Sarosh Mirza"
email = "me@saroshmirza.com"
phone = "+1-672-380-4521"
description = "Product Manager with 12+ years of experience bridging technical and business strategies in high-growth SaaS environments."

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/post/"
weight = 2
[[menu.main]]
name = "Products"
url = "/products/"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4